kind: Service
apiVersion: v1
metadata:
  name: ant-media-rtmp
spec:
  type: {{ .Values.rtmp.service.type }}
  {{- if eq .Values.rtmp.service.type "LoadBalancer" }}
  externalTrafficPolicy: Cluster
  {{- end }}
  ports:
  - name: rtmp
    port: 1935
    targetPort: 1935
    protocol: TCP
  selector:
    app: ant-media-origin
